Update Hubspot
stopthessotax/sso-wall-of-shame pull request #29
Opened 2021-09-10 19:43 UTC by Wild1145

Same PR as https://github.com/robchahin/sso-wall-of-shame/pull/245

2021-09-19 15:41 UTC, mbainter requested changes
Can you update the percentage cost?  This should be calculated with:
`(sso_pricing - base_pricing) / base_pricing * 100` -- which I believe comes out to 6856%, not 7011%.

2021-11-19 20:59 UTC, defrederick commented
I'm new here. Is this where we suggest changes?  
Splashtop SOS is only one of their products. The four offerings are:
Splashtop Business, Splashtop SOS, Splashtop Remote Support and Splashtop Enterprise.
SSO is only available with Splashtop Enterprise at $750/technician/year.  The least expensive Splashtop SOS plan is $200/tech/year.

2022-04-12 16:37 UTC, daallgeier submitted a review, later dismissed

2022-04-12 16:40 UTC, daallgeier commented
> I'm new here. Is this where we suggest changes?
> Splashtop SOS is only one of their products. The four offerings are:
> Splashtop Business, Splashtop SOS, Splashtop Remote Support and Splashtop Enterprise.
> SSO is only available with Splashtop Enterprise at $750/technician/year. The least expensive Splashtop SOS plan is $200/tech/year.

@defrederick  I have created an issue for your request.  #40

2022-04-12 19:17 UTC, mbainter commented
@daallgeier - it doesn't appear like the requested changes have been applied.  We may need to make a friendly amendment here if we want to merge it.  If I can get some time later this week and @Wild1145 hasn't already made the requested change I'll see about getting that done.

2023-04-25 01:38 UTC, doransmestad commented
Hubspot is an interesting one since (as far as I can tell) they don't charge by user count like our typical calculation.  So perhaps we measure the difference between the base tier of the professional 800/month plan and enterprise 3600/month plan for a 450% increase?   I'm assuming the Hubspot 20$/month option should fall under our exception for [single user](https://github.com/stopthessotax/sso-wall-of-shame/blob/main/index.md?plain=1#L66) plan as it feels similar in spirit.

If there are no objections to that approach I can make the updates here and get it merged in.

2025-01-01 00:14 UTC, doransmestad commented
I tweaked the submission file to match Hubspot's current pricing page based on the starter tier vs enterprise. Thanks all!

2025-01-01 00:15 UTC, merged